#! /usr/bin/env zsh
#/bin/bash


if [ "$#" -eq 0 ]; then
  echo "Error: specify the path to the App Image file"
  echo "Usage: $0 <path to the App Image file>"
  exit 1
fi

filename="$1"

# Проверяем, существует ли указанный файл
if [ ! -f "$filename" ]; then
  echo "Error: file $filename don't exist"
  exit 1
fi

# Проверяем, является ли файл AppImage
if ! file "$filename" | grep -q "AppImage"; then
  echo "Error: file $filename not an AppImage"
  exit 1
fi

# Получаем только имя файла без полного пути
appimage_name=$(basename "$filename")

# Перемещаем файл в $HOME/.local/bin с изменением имени
destination="$HOME/.local/bin/vision.AppImage"
mv "$filename" "$destination"


# Copying an Icon
(mkdir -p $HOME/.local/share/icons)
(cp icons/vision.png $HOME/.local/share/icons/vision.png)

touch $HOME/.local/share/applications/vision.desktop
echo -e "[Desktop Entry]\nName=Vision\nGenericName=Vision - anti-detection browser for traffic arbitration\nComment=Anti-detection browser for traffic arbitration\nCategories=Browser;Internet;\nExec=$HOME/.local/bin/vision.AppImage\nIcon=$HOME/.local/share/icons/vision.png\nKeywords=browser;internet;anty-detect;vision;\nNoDisplay=false\nTerminal=false" > $HOME/.local/share/applications/vision.desktop
