#! /bin/bash

echo Wisteria

# Установка пакетов из файла
sudo dnf install -y $(cat packages)

# Список директорий для копирования
directories=("cava" "foot" "lf")

# Целевая директория .config
config_dir="$HOME/.config"

# Цикл для копирования содержимого в .config
for dir in "${directories[@]}"; do
    target_dir="$config_dir/$dir"
    
    # Проверка существования целевой директории
    if [ -d "$target_dir" ]; then
        rm -rf "$target_dir"  # Удаление существующей директории
    fi
    
    mkdir -p "$target_dir"  # Создание новой директории
    cp -rf "$dir"/* "$target_dir/"  # Копирование содержимого
done

