#! /bin/bash

echo Wisteria

# Установка пакетов из файла
sudo dnf install -y $(cat packages)

# Список директорий для копирования в .config
config_directories=("cava" "dunst" "foot" "gtk-3.0" "hypr" "icons" "imv" "lf" "mpv" "neofetch" "rofi" "swaylock" "tmux" "waybar")

# Список директорий для копирования в домашнюю директорию
home_directories=("zsh")

# Целевая директория .config
config_dir="$HOME/.config"

# Цикл для копирования содержимого в .config
for dir in "${config_directories[@]}"; do
    target_dir="$config_dir/$dir"
    
    # Проверка существования целевой директории
    if [ -d "$target_dir" ]; then
        rm -rf "$target_dir"  # Удаление существующей директории
    fi
    
    mkdir -p "$target_dir"  # Создание новой директории
    cp -rf "$dir"/* "$target_dir/"  # Копирование содержимого
done

# Цикл для копирования содержимого директорий в домашнюю директорию
for dir in "${home_directories[@]}"; do
    cp -r $dir/* $HOME/.  # Копирование содержимого директории в домашнюю директорию
done
